nguage: java
jdk: oraclejdk7
before_install:
    - wget http://services.gradle.org/distributions/gradle-1.10-bin.zip
    - unzip gradle-1.10-bin.zip
    - export GRADLE_HOME=$PWD/gradle-1.10
    - export PATH=$GRADLE_HOME/bin:$PATH
script: gradle connectedInstrumentTest
