language: java
jdk: oraclejdk7

before_install:
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  - wget http://dl.google.com/android/android-sdk_r22.6.2-linux.tgz
  - tar xzf android-sdk_r22.6.2-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo y | android update sdk --no-ui --all --filter "platform-tools,android-19,build-tools-19.0.3,extra-android-support,extra-android-m2repository,extra-google-m2repository"
  - chmod +x gradlew

script:
  - ./gradlew assemble --stacktrace
# build will invoke lint, which throws NPE!
